# Generated by Django 3.2.13 on 2022-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='img/user/dog.png', max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk2\\service_desk/media/img/user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Permission'),
        ),
    ]
