# Generated by Django 3.2.13 on 2022-06-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='content_object',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
