# Generated by Django 4.0.4 on 2022-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_type',
            field=models.CharField(choices=[('SD', 'Service Desk'), ('Software', 'Software')], max_length=50, null=True),
        ),
    ]
