# Generated by Django 3.2.13 on 2022-06-21 01:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_priority_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionassociation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitionassociation_type', to='app.issuetype'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk_ya_ya\\service_desk/media/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='attachments',
            field=models.ManyToManyField(blank=True, through='app.AttachmentAssociation', to='app.Attachment', verbose_name='Attachments'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comments',
            field=models.ManyToManyField(blank=True, through='app.CommentAssociation', to='app.Comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(editable=False, help_text='Date when issue has been created', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the issue', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='escalated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Escalated'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, through='app.LabelAssociation', to='app.Label', verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='issue_priority', to='app.priority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_reporter', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_resolution', to='app.resolution', verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, default=15, on_delete=django.db.models.deletion.CASCADE, related_name='issue_status', to='app.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='Suspended'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Summarize the issue', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_type', to='app.issuetype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date when issue has been recently changed', null=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk_ya_ya\\service_desk/media/img/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk_ya_ya\\service_desk/media/img/priority', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk_ya_ya\\service_desk/media/img/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterUniqueTogether(
            name='transitionassociation',
            unique_together={('type', 'transition')},
        ),
        migrations.RemoveField(
            model_name='transitionassociation',
            name='issue_type',
        ),
    ]
