# Generated by Django 3.2.13 on 2022-06-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220626_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='operation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
