# Generated by Django 4.0.4 on 2022-05-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_status_status_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['id'], 'verbose_name': 'Issue priority', 'verbose_name_plural': 'Issue priorities'},
        ),
        migrations.AlterModelOptions(
            name='sla',
            options={'ordering': ['id'], 'verbose_name': 'SLA', 'verbose_name_plural': "SLA's"},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['id'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
    ]
