# Generated by Django 3.2.13 on 2022-06-22 01:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220621_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='types',
            field=models.ManyToManyField(through='app.TransitionAssociation', to='app.IssueType'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/img/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/img/priority', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/img/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='transition',
            name='dest_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_dest_status', to='app.status'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='src_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_src_status', to='app.status'),
        ),
    ]
