# Generated by Django 4.0.4 on 2022-05-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_priority_options_alter_sla_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status', to='app.priority'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
