# Generated by Django 3.2.13 on 2022-06-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auditlog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='content_object_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(max_length=55),
        ),
    ]
