# Generated by Django 3.2.13 on 2022-06-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticketassociation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='message',
        ),
    ]
