# Generated by Django 3.2.13 on 2022-06-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220626_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
