# Generated by Django 4.0.4 on 2022-05-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_issue_status_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('Type', models.CharField(choices=[('SD', 'Service Desk'), ('Software', 'Software')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Issue statuses',
                'db_table': 'issue_status',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='type',
            name='Type',
            field=models.CharField(choices=[('SD', 'Service Desk'), ('Software', 'Software')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status', to='app.status'),
        ),
    ]
