# Generated by Django 3.2.13 on 2022-06-22 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220622_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='src_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_src_status', to='app.status'),
        ),
    ]
