# Generated by Django 3.2.13 on 2022-06-23 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_transition_src_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterModelOptions(
            name='issuetype',
            options={'ordering': ['id'], 'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object', models.PositiveIntegerField(max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('url', models.URLField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditlog_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
