# Generated by Django 3.2.13 on 2022-06-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220626_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='field',
            new_name='content_field',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='content_object_type',
            new_name='content_object_value',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_type',
            new_name='object_value',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_field_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
