# Generated by Django 4.0.4 on 2022-05-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_attachment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='dupa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
