# Generated by Django 3.2.13 on 2022-06-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220626_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='content_field',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='content_field_value',
            new_name='content_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_object_value',
        ),
    ]
