# Generated by Django 3.2.13 on 2022-06-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220624_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['id'], 'verbose_name': 'audit log', 'verbose_name_plural': 'audit logs'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
    ]
