# Generated by Django 3.2.13 on 2022-06-24 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220624_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/attachments', validators=[django.core.validators.FileExtensionValidator(message='Extension of attached file/s is not allowed')]),
        ),
    ]
