# Generated by Django 3.2.13 on 2022-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220626_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='url',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
