# Generated by Django 4.0.4 on 2022-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_status_type_remove_status_dupa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.RemoveField(
            model_name='type',
            name='icon',
        ),
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.FilePathField(path='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/priority'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(help_text='RGB color in HEX format', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.FilePathField(path='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/tenants/'),
        ),
    ]
