# Generated by Django 3.2.13 on 2022-06-24 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, error_messages={'Attachment': 'Extension of attached file/s is not allowed'}, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
