# Generated by Django 4.0.4 on 2022-05-22 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_status_options_remove_type_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.FileField(blank=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/issuetypes', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
