# Generated by Django 3.2.13 on 2022-06-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20220626_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_value',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='session',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditlog_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
