# Generated by Django 4.0.4 on 2022-05-22 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_type_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.FileField(blank=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/priority', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.FileField(blank=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.FileField(blank=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
