# Generated by Django 4.0.4 on 2022-05-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_priority_icon_alter_tenant_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='Type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, help_text='Number of issues'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sla', verbose_name='SLA pattern'),
        ),
    ]
