# Generated by Django 3.2.13 on 2022-06-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220627_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantsession',
            old_name='user_type',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when ticket has been created', null=True, verbose_name='Created date'),
        ),
    ]
