# Generated by Django 4.0.4 on 2022-05-23 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_type_type_type_alter_tenant_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(editable=False, help_text='Date when issue has been created'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='escalated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='suspended',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date when issue has been recently changed', null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='static/custompriority', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(choices=[('service-desk', 'Service Desk'), ('software', 'Software'), ('service-desk_software', 'Service Desk + Software')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(blank=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/static/custom/images/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('service-desk', 'Service Desk'), ('software', 'Software'), ('service-desk_software', 'Service Desk + Software')], max_length=50, null=True),
        ),
    ]
