# Generated by Django 3.2.13 on 2022-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/attachments'),
        ),
    ]
