# Generated by Django 4.0.4 on 2022-05-23 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_issue_created_alter_issue_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='step',
            field=models.IntegerField(default=1, help_text='Status of order to display', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='static/custom/images/priority', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/custom/images/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/custom/images/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
