# Generated by Django 4.0.4 on 2022-05-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_status_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_issue_type', to='app.type')),
            ],
            options={
                'verbose_name': 'status association',
                'verbose_name_plural': 'status associations',
                'db_table': 'status_association',
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['step'], 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='workflow_developer',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='workflow_operator',
        ),
        migrations.AddField(
            model_name='status',
            name='issue_type_associations',
            field=models.ManyToManyField(through='app.StatusAssociation', to='app.type'),
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.AddField(
            model_name='statusassociation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status', to='app.status'),
        ),
    ]
