# Generated by Django 3.2.13 on 2022-06-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(max_length=5000, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/attachments'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
