# Generated by Django 3.2.13 on 2022-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220624_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-updated'], 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\service-desk\\service_desk/media/attachments'),
        ),
    ]
