# Generated by Django 4.0.4 on 2022-05-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_statusassociation_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_type',
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('service-desk', 'Service Desk'), ('software', 'Software')], max_length=50, null=True),
        ),
    ]
