# Generated by Django 3.2.13 on 2022-06-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220624_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
