# Generated by Django 4.0.4 on 2022-05-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_statusassociation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusassociation',
            name='resolution',
        ),
        migrations.AddField(
            model_name='status',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resolution', to='app.resolution'),
        ),
    ]
