# Generated by Django 3.2.13 on 2022-06-25 01:02

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_attachment_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='directory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to=app.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
