# Generated by Django 4.0.4 on 2022-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_statusassociation_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='transition_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
