# Generated by Django 3.2.13 on 2022-06-25 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20220625_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='associations',
        ),
        migrations.AddField(
            model_name='issue',
            name='relations',
            field=models.ManyToManyField(related_name='_app_issue_relations_+', through='app.IssueAssociation', to='app.Issue'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
