# Generated by Django 4.0.4 on 2022-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_status_transition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='transition_name',
        ),
        migrations.AddField(
            model_name='status',
            name='transition',
            field=models.CharField(blank=True, help_text='Name of transition to display before execute a specific status', max_length=50),
        ),
    ]
