# Generated by Django 3.2.13 on 2022-06-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220625_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='relations',
        ),
        migrations.AddField(
            model_name='issue',
            name='relations_in',
            field=models.ManyToManyField(related_name='_app_issue_relations_in_+', through='app.IssueAssociation', to='app.Issue', verbose_name='Relations out'),
        ),
        migrations.AddField(
            model_name='issue',
            name='relations_out',
            field=models.ManyToManyField(related_name='_app_issue_relations_out_+', through='app.IssueAssociation', to='app.Issue', verbose_name='Relations out'),
        ),
    ]
