# Generated by Django 4.0.4 on 2022-05-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_sla_options_alter_sla_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='transition',
        ),
        migrations.AddField(
            model_name='status',
            name='backward_transition',
            field=models.CharField(blank=True, help_text='Name of backward transition to previous step with smaller value', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='forward_transition',
            field=models.CharField(blank=True, help_text='Name of forward transition to next status with greater step value ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
