# Generated by Django 4.0.4 on 2022-05-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_status_transition_status_backward_transition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.AddField(
            model_name='status',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='backward_transition',
            field=models.CharField(blank=True, help_text='Name of backward transition to previous step with smaller value. There is no possibility to return in workflow if this value is blank', max_length=100, null=True),
        ),
    ]
