# Generated by Django 4.0.4 on 2022-05-23 22:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_status_description_status_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('service-desk', 'Service Desk'), ('software', 'Software')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField(help_text='Time to resolve in minutes before escalation')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.board')),
            ],
            options={
                'verbose_name': 'board column',
                'verbose_name_plural': 'board columns',
                'db_table': 'board_column',
                'ordering': ['number'],
            },
        ),
        migrations.RenameField(
            model_name='status',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='static/custom/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, help_text='Date when comment has been created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(blank=True, help_text='Date when comment has been recently changed', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='step',
            field=models.IntegerField(default=1, help_text='Order of status', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='static/custom/images/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sla'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='static/custom/images/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.CreateModel(
            name='BoardColumnAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_column_nr', to='app.boardcolumn')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_status', to='app.status')),
            ],
            options={
                'verbose_name': 'board column association',
                'verbose_name_plural': 'board column associations',
                'db_table': 'board_column_association',
                'ordering': ['column'],
            },
        ),
        migrations.AddField(
            model_name='status',
            name='board_column',
            field=models.ManyToManyField(through='app.BoardColumnAssociation', to='app.boardcolumn'),
        ),
    ]
