# Generated by Django 4.0.4 on 2022-05-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_boardcolumnassociation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcolumnassociation',
            options={'ordering': ['column'], 'verbose_name': 'board column association', 'verbose_name_plural': 'board column associations'},
        ),
    ]
