# Generated by Django 4.0.4 on 2022-05-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_boardcolumnassociation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcolumn',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.board'),
        ),
    ]
