# Generated by Django 4.0.4 on 2022-05-23 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_boardcolumn_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcolumnassociation',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_column_nr', to='app.boardcolumn'),
        ),
        migrations.AlterField(
            model_name='boardcolumnassociation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status', to='app.status'),
        ),
    ]
