# Generated by Django 4.0.4 on 2022-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_boardcolumnassociation_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(blank=True, choices=[('service-desk', 'Service Desk'), ('software', 'Software')], max_length=50, null=True),
        ),
    ]
