# Generated by Django 4.0.4 on 2022-05-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_type_board_env_type_rename_type_type_env_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SLA',
            new_name='SLAScheme',
        ),
        migrations.AlterModelTable(
            name='slascheme',
            table='sla_scheme',
        ),
    ]
