# Generated by Django 4.0.4 on 2022-05-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_sla_slascheme_alter_slascheme_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='IssueType',
        ),
    ]
