# Generated by Django 4.0.4 on 2022-05-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_type_issuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='backward_transition',
        ),
        migrations.RemoveField(
            model_name='status',
            name='forward_transition',
        ),
        migrations.RemoveField(
            model_name='status',
            name='issue_type_associations',
        ),
    ]
