# Generated by Django 4.0.4 on 2022-05-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_status_backward_transition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusAssociation',
        ),
    ]
