# Generated by Django 4.0.4 on 2022-05-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='transitions',
            field=models.ManyToManyField(through='app.Transition', to='app.status'),
        ),
    ]
