# Generated by Django 4.0.4 on 2022-05-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_transitionassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
