# Generated by Django 4.0.4 on 2022-05-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_issue_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='attachment',
        ),
    ]
