# Generated by Django 4.0.4 on 2022-05-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_attachment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
