# Generated by Django 4.0.4 on 2022-05-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolution',
            table='resolution',
        ),
    ]
