# Generated by Django 4.0.4 on 2022-05-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_resolution_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
