# Generated by Django 4.0.4 on 2022-05-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_priority_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='label',
            table='label',
        ),
    ]
