# Generated by Django 4.0.4 on 2022-05-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_attachmentassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
