# Generated by Django 4.0.4 on 2022-05-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_tenant_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of issues'),
        ),
    ]
