# Generated by Django 4.0.4 on 2022-06-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_status_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['id'], 'permissions': [('view_customer_space', 'Manage tenant as customer'), ('view_operator_space', 'Manage tenant as operator'), ('view_developer_space', 'Manage tenant as developer')], 'verbose_name': 'tenant', 'verbose_name_plural': 'tenants'},
        ),
    ]
