# Generated by Django 4.0.4 on 2022-06-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_attachment_file_alter_issuetype_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='step',
        ),
    ]
