# Generated by Django 4.0.4 on 2022-06-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_status_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='attachments',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_attachments', to='app.attachment'),
        ),
    ]
