# Generated by Django 4.0.4 on 2022-06-05 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_issue_attachments_issue_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/site/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
