# Generated by Django 4.0.4 on 2022-06-05 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_issue_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='file',
        ),
        migrations.AlterField(
            model_name='issue',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='static/site/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
