# Generated by Django 4.0.4 on 2022-06-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_remove_issue_file_alter_issue_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_priority', to='app.priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_type', to='app.issuetype'),
        ),
    ]
