# Generated by Django 4.0.4 on 2022-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_issue_priority_alter_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, help_text='Date when comment created', verbose_name='Created'),
        ),
    ]
