# Generated by Django 4.0.4 on 2022-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_usermethods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMethods',
        ),
    ]
