# Generated by Django 4.0.4 on 2022-06-06 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_delete_usermethods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Describe the issue', null=True, verbose_name='Description'),
        ),
    ]
