# Generated by Django 3.2.13 on 2022-06-10 23:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20220609_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='attachments',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachments',
            field=models.ManyToManyField(blank=True, through='app.AttachmentAssociation', to='app.Attachment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comments',
            field=models.ManyToManyField(blank=True, through='app.CommentAssociation', to='app.Comment'),
        ),
        migrations.CreateModel(
            name='LabelAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelassociation_issue', to='app.issue')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelassociation_label', to='app.label')),
            ],
            options={
                'db_table': 'label_association',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, through='app.LabelAssociation', to='app.Label'),
        ),
    ]
