# Generated by Django 3.2.13 on 2022-06-11 10:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the issue', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='issue_status', to='app.status'),
        ),
    ]
