# Generated by Django 3.2.13 on 2022-06-12 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20220611_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='env_type',
            field=models.CharField(blank=True, choices=[('service-desk', 'Service Desk'), ('software', 'Software')], max_length=50, null=True, verbose_name='Environment type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, default=15, on_delete=django.db.models.deletion.CASCADE, related_name='issue_status', to='app.status'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='env_type',
            field=models.CharField(choices=[('service-desk', 'Service Desk'), ('software', 'Software')], max_length=50, null=True, verbose_name='Environment type'),
        ),
    ]
