# Generated by Django 3.2.13 on 2022-06-12 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0076_auto_20220612_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False, editable=False)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('developer', 'Developer')], max_length=25)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantsession_tenant', to='app.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantsession_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant session',
                'verbose_name_plural': 'tenant sessions',
                'db_table': 'tenant_session',
                'ordering': ['id'],
            },
        ),
    ]
