# Generated by Django 3.2.13 on 2022-06-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_tenantsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='board_column',
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='statuses',
            field=models.ManyToManyField(through='app.BoardColumnAssociation', to='app.Status'),
        ),
    ]
