# Generated by Django 3.2.13 on 2022-06-15 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20220614_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/media/attachments', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/media/img/issue_type', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='priority',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/media/img/priority', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='F:\\Programs\\Repository\\Python\\Private\\GitHub\\service-desk\\service_desk/media/img/tenant', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
