# Generated by Django 3.2.13 on 2022-06-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20220616_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['step'], 'verbose_name': 'priority', 'verbose_name_plural': 'priorities'},
        ),
        migrations.AddField(
            model_name='priority',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
