# Generated by Django 3.2.13 on 2022-06-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_priority_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['-step'], 'verbose_name': 'priority', 'verbose_name_plural': 'priorities'},
        ),
    ]
